app/models/db.py
from app import db


class Upload(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    vdoname = db.Column(db.String, unique=True, nullable=False)

app/__init__.py
from flask import Flask, render_template, request, redirect, url_for, send_file
from flask_sqlalchemy import SQLAlchemy
import os


# create the extension
db = SQLAlchemy()


def create_app():
    # create the app
    app = Flask(__name__, template_folder='../templates/')

    # set secret key for flask session
    app.secret_key = os.urandom(24)

    # configure the SQLite database, relative to the app instance folder
    app.config["SQLALCHEMY_DATABASE_URI"] = "sqlite:///project.db"
    # initialize the app with the extension
    db.init_app(app)


    from . import views

    app.register_blueprint(views.core)


    return app

app/views.py
from flask import Blueprint, render_template, request, redirect, url_for, send_file, jsonify
from app.models.db import Upload
from app import db
import os


core = Blueprint(
    "core",
    __name__,
)


# Directory where videos will be stored (update as needed)
VIDEO_DIR = "app/static/videos/"



@core.route('/')
def home():
    # List all available videos
    vdos = db.session.execute(db.select(Upload.vdoname).order_by(Upload.id)).scalars()
    return render_template('home.html', videos=vdos)

@core.route('/upload', methods=['GET', 'POST'])
def upload():
    if request.method == 'POST':
        video = request.files['video']
        if video:
            try:
                video.save(VIDEO_DIR + video.filename)
                upload = Upload(vdoname = video.filename)
                db.session.add(upload)
                db.session.commit()
            except:
                return jsonify({'ERROR': 'Please check if file already uploaded.'})

    return redirect(url_for('core.home'))

@core.route('/watch/<video_name>')
def watch(video_name):
    return render_template('watch.html', video_name=video_name)

@core.route('/video/<video_name>')
def video(video_name):
    return send_file( "static/videos/"+ video_name, as_attachment=True)

templates/home.html
<!DOCTYPE html>
<html>
<body>
    <h1>Basic Video Sharing Service</h1>
    <h2>Available Videos:</h2>
    <ul>
        {% for video in videos %}
        <li><a href="{{ url_for('core.watch', video_name=video) }}">{{ video }}</a></li>
        {% endfor %}
    </ul>
    <h2>Upload Video:</h2>
    <form method="POST" action="/upload" enctype="multipart/form-data">
        <input type="file" name="video" accept=".mp4">
        <input type="submit" value="Upload">
    </form>
</body>
</html>

templates/watch.html
<!DOCTYPE html>
<html>
<body>
    <h1>Watch Video</h1>
    <video width="640" height="360" controls>
        <source src="{{ url_for('core.video', video_name=video_name) }}" type="video/mp4">
        Your browser does not support the video tag.
    </video>

    <br/>
    <a href="/">back</a>
</body>
</html>